Azure/go-shuttle

README.md
Adding documentation for the functionality added in #23
=> doc: message lock renewal and concurrent message handling

integration/concurrentcreate_test.go, listener/listener.go, publisher/publisher.go
similarly to #28, retry on subscription create when calling Listen(...)
=> retry on subscription create

listener/options.go, listener/options_test.go, publisher/options.go, publisher/options_test.go, publisher/publisher.go
add option to set azure environment on sb namespace
=> add azure environment option

handlers/messagecontext_test.go
=> Add unit test for context cancellation occuring before with deadline is exceeded

listener/alias.go, publisher/queue/alias.go, publisher/topic/alias.go
Adding aliases for backwards compatibility
=> Add aliases to support existing users on next release

go.mod, go.sum
bump sb dependencies that includes some bug fixes
=> bump servicebus, amqp, and some side dependencies

go.mod, go.sum
=> bump autorest

go.mod, go.sum
=> fixing dependabot warning

message/deadletter.go
Allows for a given message to be put onto the deadletter queue
=> Adding DeadLetter functionality to a message

integration/publisher_queue_test.go, queue/publisher/options.go
adding ability to set a custom queue for DLQ forwarding
=> Adding forward DLQ to management option

integration/publisher_queue_test.go
fixing typo in parallel testing
=> fixing typo for parallel testing

common/options/publisheropts/options.go
=> Expose ScheduleAt publisher option

v2/e2e/e2e_test.go, v2/go.mod, v2/go.sum, v2/managedsettling.go, v2/managedsettling_example_test.go, v2/marshaller.go, v2/marshaller_test.go, v2/processor.go, v2/processor_fake_test.go, v2/processor_test.go, v2/sender.go, v2/sender_test.go, v2/settlehandler.go, v2/settlehandler_example_test.go, v2/tracing/tracing.go
although the folder name is v2, the package name should be "shuttle"
this fixes that. so that usage is a bit nicer.
=> make package name not be v2

v2/go.mod, v2/go.sum
=> bump azcore

v2/sender.go, v2/sender_test.go
bug-fix: making Marshaller field settable so user can provide their own marshallers.
=> make marshaller field settable

v2/sender.go, v2/sender_test.go
adding a setter for TimeToLive in sender.go
=> Adding setMessageTTL to sender.go

v2/tracing/tracing.go
=> Adding nil check for correlationID

.github/workflows/golangci-lint.yaml, v2/e2e/e2e_test.go, v2/managedsettling_example_test.go, v2/processor.go, v2/processor_test.go, v2/settlehandler_example_test.go, v2/settlehandler_test.go
=> fix panic handler + lots of UT

v2/managedsettling.go, v2/managedsettling_test.go
OnError option allows to override the ManagedSettlingHandler error handling pre-settlement.
The options struct is passed in, so that other options can be used inside the implementation
=> [feat] add OnError hook to ManagedSettlingHandler

v2/sender.go, v2/sender_test.go, v2/tracing_test.go
Expose Sender batch operations
=> feat: Expose batch operations

.pipelines/azure-pipelines.yml
az pipeline is outdated and only runs on main.
disable its triggers until it's back in order
=> disable az pipeline until we fix it

v2/lockrenewer.go, v2/lockrenewer_test.go, v2/processor.go, v2/processor_test.go
separate lockrenewer from processor to clean up before next PR
=> [chore] move lockrenewer out

v2/sender.go
Add the prometheus metrics to the sender
=> Adding metric to sender

v2/go.mod, v2/go.sum
updating to newest version of servicebus sdk
=> deps: updating azure-sdk-for-go version

v2/go.mod, v2/go.sum, v2/metrics/processor/types.go, v2/metrics/sender/types.go
bump prom client-go package to 0.5.0
fix go vet
=> bump github.com/prometheus/client_model to 0.5.0

v2/metrics/sender/types.go, v2/metrics/sender/types_test.go
Add method to allow resetting sender metrics when we replace a sender
=> Add method to reset sender metrics

v2/lockrenewer.go, v2/lockrenewer_test.go, v2/processor_test.go
Fix for https://github.com/Azure/go-shuttle/issues/241
=> Add option to timeout during LockRenewal calls

v2/managedsettling.go, v2/settlehandler.go
Add timeout to all settlement calls to prevent bad connection
=> [settle] Add timeout to all settlement calls

v2/go.mod, v2/go.sum
bump servicebus sdk to bring in the latest fixes
=> [chores]⬆️ bump to latest servicebus sdk

v2/sender.go, v2/sender_test.go
Support sender SetSubject() and SetTo() options
=> [sender] Support sender SetSubject() and SetTo() options
