listener/listener.go

Expose a listener API to get real time TopicEntity. The caller can get the useful information such as the count of active messages in the topic with the TopicEntity.

Expose a listener API to get real time active message count

---

integration/pubsub_test.go
listener/listener.go

The variable handler in listenerHandle comes from the outside. When the first message is handled, handler is changed, and it can't handle the following messages any more.

Fix the issue that only the first message is handled

---

go.mod
message/abandon.go
message/complete.go
message/error.go
message/handler.go
message/message.go
message/tracing.go

Message handlers (abandon and complete don't return errors to the clients. Let's trace errors to facilitate troubleshooting.
We'd like to enable trace based on "github.com/devigned/tab", which is same as service bus.

Add traces when handling messages

---

message/abandon.go
message/complete.go
message/handler.go

It looks like tab.For(ctx).Error doesn't really work to add attributes. Let's use span.AddAttributes explicitly.

Change the way to add fields into spans

---

Dockerfile
README.md
integration/pubsub_test.go
internal/servicebus/namespace.go
listener/listener.go
message/retrylater.go

Right now retry later is broken because it will 
1) Block other messages from coming in
2) Block till after lock duration which means completes error  and messages don't finish

RetryLater should abandon on a seperate go routine

---

integration/concurrentcreate_test.go
publisher/publisher.go

Simple retry on Put topic to avoid 409 when concurrent publisher start up.

feat: add a simple retry on ensureTopic

---

listener/listener.go
listener/options.go
publisher/options.go
publisher/publisher.go

`listener.go` and `publisher.go` are becoming too large.
splitting the options out to keep them leaner

chore: split options out from main publisher/listener files

---

handlers/concurrent.go
handlers/lockrenewer.go
handlers/messagecontext.go
handlers/shuttleadapter.go

I noticed that if a concurrent handler was being used that the error returned by any child handler of the concurrent handler would be ignored as there was no way to pass the error out of the go-routine and back to the parent function.
So, in this PR I am switching to panic on creation + making struct creation have to flow through the constructor in order to make sure that any error would be caught within the creation step and panic

Improving safety of Handler creation

---

Makefile
scripts/test-setup.sh

In the case where the `default az-cli subscription id` != `$AZURE_SUBSCRIPTION_ID`, the current `test-setup` and `integration` scripts will fail.
`MANAGED_IDENTITY_RESOURCE_ID` in `test-setup.sh` will be constructed incorrectly due to the mismatch.
This PR fix just propagates the `AZURE_SUBSCRIPTION_ID` to all `az-cli` calls as an explicit `--subscription` flag.

Add Explicit Subscription Flags for AZ CLI commands

---

.gitignore
integration/pubsub_test.go
listener/options.go

this allows the consumer to define a type filter on the subscription by providing an instance of the event : 
```golang
l, err := listener.New(suite.listenerAuthOption,
listener.WithSubscriptionName("subEventTypeFilter"),
listener.WithTypeFilter(&testEvent{}))
```
`listener.WithTypeFilter(&testEvent{}))` 
is a shortcut for : 
`listener.WithFilterDescriber("testFilter", servicebus.SQLFilter{Expression: "type LIKE 'testEvent'"}))`
It allows to optimize the filter to avoid the SQLFilter in the future

feat: add event type filter option helper

---

listener/options.go

currently lockduration and max delivery count need to be set use the same function, separating them.

Separate lock duration and max count management option

---

listener/options.go
publisher/options.go

mutate the namespace object instead of overriding it
this allows to compose more options without caring about the order to apply them

do not override namespace when applying options on it

---

Dockerfile
docker-compose.yaml
go.mod
integration/publisher_test.go
publisher/publisher.go

When the underlying tcp connection is lost, the next publish call fails with a network error. The connection will never be re-established by AMQP, leaving the publisher in a truly broken state. the only available recourse for the application code is to re-create the publisher.
This PR adds recovery code in the `Send` func to rebuild the underlying topic and retry to send the message when we meet a network error that is not temporary, or when it is recognized as a timeout (happens when tcp has been closed).

add publisher recovery on network error

---

integration/concurrentcreate_topic_test.go
integration/issue_topic_test.go
integration/listener_test.go
integration/publisher_queue_test.go
integration/publisher_topic_test.go
integration/pubsub_topic_test.go
integration/suite_queue_test.go
integration/suite_topic_test.go
internal/test/test.go
publisher/queue/options.go
publisher/queue/options_test.go
publisher/queue/publisher.go
publisher/topic/options.go
publisher/topic/options_test.go
publisher/topic/publisher.go

Implementation and refactor to support ServiceBus Queues.
This PR focuses on establishing the pattern for creating a Queue Publisher -- the patterns decided on will follow for the Listener implementation/refactor.

Queue Publisher Implementation

---

docker-compose.yaml
go.mod
handlers/shuttleadapter.go
message/error.go
message/handler_test.go
publisher/errorhandling/recovery.go
publisher/errorhandling/recovery_test.go
publisher/queue/publisher.go
publisher/topic/publisher.go
run-integration.sh

We've identified that amqp-internal error are not transient as the message lets you believe.
restarting the process was the only way to fix it.
this attempts to handle the error the same way as for a network errors.
this could be moved into the servicebus sdk to follow these other error handling scenarios:
https://github.com/Azure/azure-service-bus-go/blob/319bf88d3749af809309efdfb6498a790d5b0f44/sender.go#L251-L268
It should also be checked with the Servicebus team as the error message states incorrectly to "retry later".

Recover from amqp-internal error by recreating connection

---

handlers/lockrenewer_test.go
handlers/messagecontext.go
handlers/messagecontext_test.go

When an incoming has a TTL set, the message context handler was returning a deadline context, but with the cancel func from the original cancel context.
this means that the wrong cancel was being called and that the LockRenewer was running indefinitely in the background, creating sessions on the link that never got closed. it eventually reaches "max session" and stops working.
This returns the correct context, which will stop the renewer as soon as a message is done being handled.

fix deadline context leak

---

common/errorhandling/recovery.go
common/errorhandling/recovery_test.go

The PR is self explaining, the prefix verification arguments were in the wrong order. 
This caused the service to sometimes avoid reconnecting. (Depending if it caught the initial read timeout).

Fix amqp-internal error recovery detection

---

prometheus/listener/types.go
prometheus/listener/types_test.go

Adds an informer to the prometheus/listener package to allow checking for metric value within the service.

feat: add lockRenewedFailureCount informer

---

v2/otel/otel.go
v2/otel/otel_test.go
v2/processor.go
v2/tracing.go
v2/tracing_test.go

move the shuttle dependent bits to the v2 root to avoid circular dependency
rename tracing package to otel

chore: [tracing] move tracing things around

---

v2/sender.go

Allow to configure opentelemetry tracing propagation as a sender option

add sender level option for tracing

---

v2/managedsettling.go
v2/managedsettling_example_test.go
v2/managedsettling_test.go

use an interface in the ManagedSettling to simplify consumer code.

:recycle: use an interface for the ManagedSettlingHandler

---

.github/workflows/golangci-lint.yaml
.github/workflows/v2-build-and-ut.yaml
v2/go.mod
v2/lockrenewer.go
v2/lockrenewer_test.go
v2/managedsettling_test.go
v2/processor.go
v2/processor_fake_test.go
v2/processor_test.go

The current lock-renewer is taking a relaxed approach to deciding when to stop attempting to renew. 
It exits the renewal loop on context cancellation only. all other errors are logged, but do not cause the renewer to stop.
This relies on the fact that the processor creates a separate child context per message, so when the message processing is done, the context will eventually be disposed of, causing the matching lock renewer to stop as well.
downside:
- it leaves a window where the handler has sent a message disposition (abandoned, completed, etc..) and has **not** exited yet. In these cases, the renewer can call Renew and get back an error because the lock is lost.
- if a serverside event causes unrecoverable errors, the lock renewer would also rely on context cancelation.
This PR …

[fix] Stop lock-renewer when we know we can

---

v2/e2e/e2e_test.go
v2/lockrenewer.go
v2/lockrenewer_test.go
v2/managedsettling_example_test.go
v2/processor.go
v2/settlehandler_example_test.go

The lock renewer can stop for 2 reasons. 
- when the message handler is finished
- when an error occurs and we know we can't renew the lock.
in both these cases, we are better off dropping the message processing, because the message might get picked up by another handler at anytime. This adds a child context at the lock renewer level and cancels it when the lock renewer stops.
- New constructor for the lock renewer middleware to wrap options as a type
- Deprecate old constructor
- Add CancelMessageContextOnStop option
- Default to true in new constructor, false if deprecated constructor is used.
- Improve tests

✨ Cancel message context when lockrenewer stops

---

v2/lockrenewer.go
v2/lockrenewer_test.go

There was a bug in the peeklock renewer that would cause the message context cancellation func reference to be overridden when concurrent messages are processed.
This was introduced in 2.4.0 when tightening the handling of context cancelation per messages.

🐞 fix closure in PeekLockRenewer that was causing context cancelation to impact another message

---

v2/lockrenewer.go
v2/logging.go
v2/logging_test.go
v2/managedsettling.go
v2/processor.go

Remove the Timestamp prefix in the log helper function.
It should only be added on the internal printlogger for console log testing

🔊 fix log format

---

v2/sender.go
v2/sender_test.go

- Add SendTimeout option on SenderOptions
- If no timeout is set, use 10s default value
- Disable automatic context timeout wrapping if value is negative

[feat]✨ Add SendTimeout option on sender

---

v2/sender.go
v2/sender_test.go

Adding explicit context handling since azure sdk has shown to not respect timeouts

fix: respecting context cancelation since sdk does not

---

v2/sender.go

Traces have shown send can succeed after up to 26s due to internal recovery code after idling.
defaulting to 30s to account for this.

bump send timeout to 30s

---

v2/go.mod
v2/go.sum

https://github.com/Azure/go-amqp/releases/tag/v1.0.2
> - Fixed an issue that could cause frames to be sent even when the provided context.Context was cancelled.
> - Fixed a potential hang in Sender.Send() that could happen in rare circumstances.
> - Ensure that Sender's delivery count and link credit are updated when a transfer fails to send due to context cancellation/timeout.

🔼[chore] require go-amqp@v1.0.2 that include latest fixes for SDK

---

v2/sender.go
v2/sender_test.go

This change is to explicitly check if the context is already canceled before attempting any Send operation. 
This will protect our send failure metrics from callers who may not respect a context properly before passing it to us. 
It also helps us isolate where timeouts are occurring within the stack.

adding explicit context check before sends

---

v2/lockrenewer.go
v2/lockrenewer_test.go
v2/metrics/processor/types.go
v2/metrics/processor/types_test.go

🐛 fix: do not count context errors as failure to renew a lock

---

v2/managedsettling.go
v2/processor.go
v2/processor_test.go
v2/utils.go

This PR enables retries on `Processor.Start()`. Users can configure this with `StartMaxAttempt` and `StartRetryDelayStrategy`. `Start()` returns the last error encountered while starting the processor

Enable Configuration of Processor.Start() Retries

---

README.md
v2/lockrenewer.go
v2/lockrenewer_test.go
v2/managedsettling_example_test.go
v2/processor.go
v2/processor_test.go
v2/settlehandler_example_test.go

- Refractor `NewLockRenewalHandler` to `NewRenewLockHandler`. The refractor gets rid of the lockRenewer argument in the constructor and instead uses the settler passed down from the handler function. 
- Deprecate `NewLockRenewalHandler`
- The refractor also enables compatibility with MultiProcessor. The lock renewal handler now will automatically take in the correct settler for each receiver in the MultiProcessor.
- Added UT to verify compatibility.

Refractor LockRenewer and Enable Compatibility with MultiProcessor

---

v2/go.mod
v2/lockrenewer.go
v2/logging.go
v2/logging_test.go
v2/managedsettling.go
v2/processor.go
v2/settlehandler.go

Adapt slog and split logs into different levels

Split logs into different levels

---

v2/sender.go
v2/sender_test.go

Rename sender.FailOver() to sender.SetAzSender()

Rename sender.FailOver() to sender.SetAzSender()

---

v2/lockrenewer.go
v2/metrics/processor/types.go
v2/metrics/processor/types_test.go
v2/metrics/registry_test.go

Add prom metric for lock renewal timeouts

[lockrenewer] Add prom metric for lock renewal timeouts

---

v2/sender.go
v2/sender_test.go

Expose AzSender Close()
After calling SetAzSender(), we want to be able to close the previous underlying AzSender connection to avoid taking up the connection quota.

Expose az sender Close()

---

v2/processor.go
v2/processor_test.go

The SDK's Receive() call has a [20ms wait time](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus#ReceiveMessagesOptions) after it fetches the first message, and all the remaining goes into a message releaser that gives them back to the server. In situations where MaxConcurrency is configured to a high number, we see lots of messages getting returned to the server by the message releaser
This PR adds a MaxReceiveCount option to the ProcessorOptions struct.

[processor] Add MaxReceiveCount option
